language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update

install:
  - python -m pip install --upgrade pip
  - pip install telebot cairosvg && chmod +x bgmi

script:
  - python3 main.py
